language: node_js
node_js:
  - "12"

branches:
  only:
  - master
    
script:
  - npm install
  - npm install surge -g
  - node_modules/.bin/gitbook install
  - node_modules/.bin/gitbook build
  - node_modules/.bin/surge --domain http://elasticsearch-2d-courseware.surge.sh/ --project ./_book